version: '3'

services:

  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - bookstore

  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    networks:
      - bookstore
  db:
    image: postgres
    environment: 
        POSTGRES_DB: 3005BookStore
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
    volumes:
#        - database_postgres:/var/lib/postgresql/data
        - ./sql/ddl.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
        - bookstore
        
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
        - db
    ports:
        - "5555:80"
    links:
        - db
    environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: 1234
    restart: unless-stopped
    networks:
      - bookstore

volumes:
    database_postgres:

networks:
    bookstore:
        driver: bridge